name: Build and Push Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  main:
    name: Build and push services

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Context
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push enrollment service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/EnrollmentService/enrollment-api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.ENROLLMENT_SERVICE}}:latest


      - name: Build and push notification service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/NotificationService/notification-api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.NOTIFICATION_SERVICE}}:latest
      - name: Build and push subject service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/SubjectService/subject-api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.SUBJECT_SERVICE}}:latest

      - name: Build and push user service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/UserService/user-api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.USER_SERVICE}}:latest

  
  
